### ISSUE TITLE
Compatibilidade com Zepto

### ISSUE THREAD

**Issue by mcarneiro** [Javiani/Validator2#1]
Fui implementar a Validator num projeto que usa a Zepto e percebi que ela não disparava os eventos. Isso se dá pelo Zepto apenas disparar eventos com "namespace" no `triggerHandler`. O problema do `triggerHandler` nesse caso seria não propagar o evento para os elementos pais, ex.: se eu quisesse que o body mudasse de cor quando houvesse erro em algum formulário da tela, apenas precisaria aplicar o evento no `body`...

Vi que uma solução seria utilizar o ":" como separador, mas durante meus testes, vi que no Zepto ele perde o sentido do namespace, já que se eu dou um `.off('validator')` ele não remove todos os eventos / sub-eventos, como aconteceria no jQuery.

De qualquer forma, ambos os jeitos funcionariam, cada um com suas limitações. Criei um branch com a solução do ":" como separador para usar no meu projeto e é possível ver a comparação aqui: https://github.com/mcarneiro/Validator2/compare/zepto-compatibility?expand=1

Não fiz muito mais testes no código para ver se toda a implementação está idêntica no Zepto, mas de qualquer forma, acho que vale a pena dar o suporte.

**Comment by Javiani** [comment]
Oi Deds, 

Atualizei a validator com namespace usando ":", acho que neste caso é a melhor opção, já que na documentação deles eles sugerem usar ":". 

Mesmo assim, na minha opinião acho que deveriam seguir o mesmo padrão do jQuery. Se um dia isso acontecer, removo do validator esses separadores extras.

Atualizei também os arquivos de exemplo, estavam errados e deixei a zepto como base para testes.

[]'s
